version: '3.9'
services:
 
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_movies
    ports:
      - '3001:3001'
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
  
  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
  
  
  redis:
    image: redis
    hostname: redis

    restart: always
    env_file:
      - .env
    ports:
      - '6379:6379'
    command: redis-server
