export enum MovieEnum {
  MAX_NAME_LENGTH = 50,
  MAX_DIRECTOR_NAME_LENGTH = 100,
  MAX_CATEGORY_NAME_LENGTH = 20,
  MAX_ACTORS_NAME_LENGTH = 100,
  MAX_DESCRIPTION_LENGTH = 256,
  MAX_YEAR = 2023,
  MIN_YEAR = 1824,
}
